using Godot;

namespace GodotTests.ManualTests;

/// <summary>
/// Test fails if the temporary mono object generated by the Godot Editor fails with 'Cannot get path of node as it is not in a scene tree', followed by a null reference exception.
/// Test passes if the Editor can be opened and scene loaded* without the error showing in the output console.  (* occurs mostly on Editor startup but load scene to make sure)
/// Ensure build is successful before running test.
///
/// Additional notes:
///  - If Export value set via tscn, error also occurs on open/save
///  - Issue occurs in getter for temp mono object, but setter for open/save
///  - The proposed fix (GetNodeOrNull with ?.) works, but means no error if null
/// </summary>
[Tool, SceneTree]
public partial class SceneTreeUsageInExportProperty : Control
{
	[Export]
	public string LabelText
	{
		get => _.Label?.Text;
		set
		{
			if (_.Label is null) return;
			_.Label.Text = value;
		}
	}
}
