using Godot;

namespace GodotTests.TestScenes.ManualTests
{
    /// <summary>
    /// Test fails if the temporary mono object generated by the Godot Editor fails with 'Cannot get path of node as it is not in a scene tree', followed by a null reference exception.
    /// Test passes if the Editor can be opened and scene loaded* without the error showing in the output console.  (* occurs mostly on Editor startup but load scene to make sure)
    /// Ensure build is successful before running test.
    /// </summary>
    [SceneTree]
    public partial class SceneTreeUsageInExportProperty : Control
    {
        [Export]
        public string LabelText
        {
            get => _.Label.Text;
            set => _.Label.Text = value;
        }
    }
}
